### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [helperdiscord/centra#16]
## Bug Description

Never install this directly, though from the error I see it may be a dependency of erela.js. Now whenever I start my program, my console errors with:
```
/Users/ragnar/GitHub/Ragnarok-Discord/node_modules/petitio/dist/index.js:1
var gt=Object.create,we=Object.defineProperty,yt=Object.getPrototypeOf,bt=Object.prototype.hasOwnProperty,wt=Object.getOwnPropertyNames,Tt=Object.getOwnPropertyDescriptor;var Et=t=>we(t,"__esModule",{value:!0});var $=(t,e)=>()=>(e||(e={exports:{}},t(e.exports,e)),e.exports);var kt=(t,e,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let s of wt(e))!bt.call(t,s)&&s!=="default"&&we(t,s,{get:()=>e[s],enumerable:!(r=Tt(e,s))||r.enumerable});return t},J=t=>kt(Et(we(t!=null?gt(yt(t)):{},"default",t&&t.__esModule&&"default"in t?{get:()=>t.default,enumerable:!0}:{value:t,enumerable:!0})),t);var Ne=$((Zt,_e)=>{"use strict";var{HTTPParser:St}=process.binding("http_parser");_e.exports=St});var Te=$((er,Pe)=>{Pe.exports={kUrl:Symbol("url"),kWriting:Symbol("writing"),kResuming:Symbol("resuming"),kQueue:Symbol("queue"),kConnect:Symbol("connect"),kIdleTimeout:Symbol("idle timeout"),kIdleTimeoutValue:Symbol("idle timeout value"),kKeepAli

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/ragnar/GitHub/Ragnarok-Discord/node_modules/erela.js/dist/structures/Node.js:18:35)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

## Reproducible By

N/A - Dependancy updated causing error

## Environment

Running program on Mac OS - Node.js version 12.16.1

**Comment by RagnarLothbrok-Odin** [comment]
Appears that the new update requires a newer version of node

**Comment by lveneris** [comment]
@RagnarLothbrok-Odin Apologies, I didn't see this until just now. While we do recommend updating, we acknowledge that Node 12 is not EOL until next year, and will be adjusting our compilation to support it in a future version. Thank you for your issue :)
