### ISSUE TITLE
SyntaxError: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by zairullahdev** [helperdiscord/centra#41]
## Bug Description

Caused by erela js, using nodejs 1.18.10

## Reproducible By
Erela js search

## Expected Behavior

it search the song

## Logs & Screenshots
```logs
Lava-Music Logs | Mon 31-10-2022 06:30:46.0210 [::]  Player for the Bot created!
Lava-Music Logs | Mon 31-10-2022 06:30:46.7160 [::]  Logging into the Bot ...
Lava-Music Logs | Mon 31-10-2022 06:30:48.5290 [::]  Shard #0 Ready                                  Lava-Music Logs | Mon 31-10-2022 06:30:48.5340 [::]  Discord Bot is now online and ready to be used! Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Bot User: Voidy#6320                            Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Guild(s): 3 Servers
Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Watching: 60 Members                            Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Prefix: <@997723699111280673>                   Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Commands: 97                                    Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Discord.js: v13.9.2
Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Node.js: v18.10.0                               Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Plattform: android arm64                        Lava-Music Logs | Mon 31-10-2022 06:30:48.5380 [::]  Memory: 22.98 MB / 84.34 MB
Lava-Music Logs | Mon 31-10-2022 06:30:48.5570 [::]  Set the first Status Text
Lava-Music Logs | Mon 31-10-2022 06:30:49.3230 [::]  Node connected :: 
Lava-Music Logs | Mon 31-10-2022 06:30:50.3970 [::]  Autoresume - Voice Channel is either Empty / no Listeners / got deleted
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (/data/data/com.termux/files/home/project/discord-js-lavalink-Music-Bot-erela-js/node_modules/petitio/dist/index.js:30:574)
    at ke.json (/data/data/com.termux/files/home/project/discord-js-lavalink-Music-Bot-erela-js/node_modules/petitio/dist/index.js:30:2499)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                    (node:7833) [DEP0160] DeprecationWarning: The multipleResolves event has been deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

## Environment

Termux Android, NodeJS 1.18.10

**Comment by dzlandis** [comment]
Can reproduce issue using any NodeJS version above 16.6 (such as 16.17 and 16.18), perhaps a duplicate of #36 (which needs to be reopened).

**Comment by FC5570** [comment]
I have the same issue on node v18.11.0 and petitio v1.4.0.

**Comment by SummerToast** [comment]
Well anyone have any idea how to fix this?

**Comment by dzlandis** [comment]
@SummerToast install an earlier version of NodeJS for now I suppose. You can use something like `nvm` to make it easier.
